// Generated by CoffeeScript 1.6.1
(function() {
  var catcherr, reportError;

  reportError = function(error) {
    if ((error != null ? error.stack : void 0) != null) {
      return Meteor._debug(error.stack);
    } else if ((error != null ? error.message : void 0) != null) {
      return Meteor._debug(error.message);
    } else {
      return Meteor._debug(error);
    }
  };

  catcherr = function(fn, onFailed) {
    try {
      return fn();
    } catch (error) {
      reportError(error);
      if (typeof onFailed === "function") {
        onFailed();
      }
    }
  };

  (this.awwx || (this.awwx = {})).err = {
    reportError: reportError,
    catcherr: catcherr
  };

}).call(this);
