// Generated by CoffeeScript 1.6.1
(function() {

  Package.describe({
    summary: "Centralized error reporting"
  });

  Package.on_use(function(api) {
    return api.add_files('err.js', ['client', 'server']);
  });

}).call(this);
